# Generated by Django 6.0 on 2026-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_type_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_column='category_type', max_length=10),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_type',
            new_name='type',
        ),
    ]
